### ISSUE TITLE
Web API

### ISSUE THREAD

**Issue by edwinvdpol** [Retrospected/com.sony.bravia.smarttv#3]
Hi there,

Why aren't you using the [REST API](https://pro-bravia.sony.net/develop/integrate/rest-api/spec/) ?

You already tried to make this work?

**Comment by Retrospected** [comment]
I think this will not work on my (old) Bravia, it only supports the IRCC-IP service
Basically i'm using the requests I've intercepted off the Sony TV remote app (Video & TV SideView)
