### ISSUE TITLE
after OREO update bravia 

### ISSUE THREAD

**Issue by HansS63** [Retrospected/com.sony.bravia.smarttv#4]
After the oreo update from sony this app won't communicate with my Sony TV.
I have al the settings checkt and tv have static IP with I put into the app on my homey. I hope it will be fixed soon. I love the app...

Homey 2.0.5.rc3 
Bravia app 2.0.2

Thanks for all the good work!!

**Comment by Retrospected** [comment]
hey, i think you’re mixing the ‘smarttv’ app with the ‘androidtv’ app of android. My app is used by the older Bravia tv’s that weren’t using android yet!

**Comment by HansS63** [comment]
Okay, sorry man, i had 2 apps for sony on  Homey. Then is was the other app. And tbat one put tje tv on and off...
